apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress-namespace
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: wordpress-namespace
      chart: wordpress
      version: 15.2.12
    interval: 1m0s
    values:
    wordpressPassword: "123456"
    service:
      type: ClusterIP
